agent {
    data_dir = "/run/spire/data"
    log_level = "DEBUG"
    server_address = "spire-server"
    server_port = "8081"
    socket_path = "/tmp/spire-agent.sock"
    # trust_bundle_path = "/run/spire/data/bundle.crt"
    trust_domain = "example.org"
    admin_socket_path = "/run/spire-agent-admin.sock"
    insecure_bootstrap = true
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "disk" {
        plugin_data {
            directory = "/run/spire/data"
    }
}

    WorkloadAttestor "unix" {
        plugin_data {
            discover_workload_path = true
        }
    }
}
