agent {
    data_dir = "/run/spire/data"
    log_level = "DEBUG"
    server_address = "spire-server"
    server_port = "8081"
    socket_path = "/tmp/spire-agent.sock"
    trust_domain = "example.org"

    trust_bundle_path = "/run/spire/bundle/bundle.crt"
    insecure_bootstrap = false
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "disk" {
        plugin_data {
            directory = "/run/spire/data"
        }
    }

    WorkloadAttestor "docker" {
        plugin_data {}
    }

    WorkloadAttestor "unix" {
        plugin_data {
            discover_workload_path = true
        }
    }
}