networks:
  kms-internal-net:
    name: kms_internal_net
    driver: bridge

  sec-net:
    name: kms_sec_net
    driver: bridge

  target-admin-net:
    name: kms_target_admin_net
    driver: bridge
