# docker-compose.yml

x-common-healthcheck: &common-healthcheck
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 15s

services:
  postgres:
    image: postgres:18.3-alpine
    container_name: kms_db
    networks:
      - kms-internal-net
    ports:
      - "127.0.0.1:5440:5432"
    environment:
      POSTGRES_DB: ${DATABASE__NAME:-kms_db}
      POSTGRES_USER: ${DATABASE__ROOT_USER:-kms_root_user}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_root_pass
      POSTGRES_MIGRATOR_USER: ${DATABASE__MIGRATOR_USER:-kms_migrator_user}
      POSTGRES_APP_USER: ${DATABASE__USER:-kms_app_user}
      PGDATA: /var/lib/postgresql/data/pgdata
    secrets:
      - db_root_pass
      - kms_migrator_db_pass
      - kms_app_db_pass
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./scripts/init-user.sh:/docker-entrypoint-initdb.d/01-init-user.sh:ro
    healthcheck:
      <<: *common-healthcheck
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DATABASE__ROOT_USER:-kms_root_user} -d ${DATABASE__NAME:-kms_db}",
        ]

  kms-migrate:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: kms_migrate
    entrypoint: []
    environment:
      - RUST_LOG=${RUST_LOG:-debug}
      - DATABASE__HOST=postgres
      - DATABASE__PORT=5432
      - DATABASE__NAME=${DATABASE__NAME:-kms_db}
      - DATABASE__USER=${DATABASE__MIGRATOR_USER:-kms_migrator_user}
      - DATABASE__PASSWORD_FILE=/run/secrets/kms_migrator_db_pass
      - MIGRATIONS_DIR=/app/crates/kms-migrate/migrations
    secrets:
      - kms_migrator_db_pass
    volumes:
      - .:/app
      - cargo_cache:/usr/local/cargo/registry
      - target_cache:/app/target
    networks:
      - kms-internal-net
    depends_on:
      postgres:
        condition: service_healthy

  vhsm-daemon:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vhsm_daemon
    entrypoint: []
    command: cargo run -p vhsm-daemon --bin vhsm-daemon
    environment:
      - RUST_LOG=${LOG__LEVEL:-debug}
      - LOG__FORMAT=${LOG__FORMAT:-pretty}
      - VHSM__SOCKET_PATH=/run/vhsm/vhsm.sock
    volumes:
      - .:/app
      - cargo_cache:/usr/local/cargo/registry
      - target_cache:/app/target
      - vhsm_sockets:/run/vhsm

volumes:
  postgres_data:
    driver: local
  kms_ceremony_data:
    driver: local
  vhsm_sockets:
    driver: local
  cargo_cache:
    driver: local
  target_cache:
    driver: local

secrets:
  db_root_pass:
    file: ./secrets/.db_root_password
  kms_app_db_pass:
    file: ./secrets/.kms_app_password
  kms_migrator_db_pass:
    file: ./secrets/.kms_migrator_password

networks:
  kms-internal-net:
    name: kms_internal_net
    external: true
  sec-net:
    name: kms_sec_net
    external: true
  target-admin-net:
    name: kms_target_admin_net
    external: true
