[package]
name = "vhsm-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.38", features = ["full"] }
serde_json = "1.0"
aes-gcm = "0.10"
rand = "0.8"
hex = "0.4"
base64 = "0.23.1"
tracing = "0.1"
tracing-subscriber = "0.3"
zeroize = "1.8"
kms-core = { path = "../kms-core" }
rcgen = "0.9"
x509-parser = "0.14"
ring = "0.17"
yasna = "0.5"
chrono = { version = "0.4", features = ["serde"] }