[package]
name = "kms-db"
version = "0.1.0"
edition = "2024"

[dependencies]
# Unique dependencies for this crate
base64 = "0.23.1"
rand = "0.8"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json", "macros"] }

# Shared dependencies inherited from the workspace
chrono = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
uuid = { workspace = true }
zeroize = { workspace = true, features = ["zeroize_derive", "serde"] }
