[package]
name = "kms-migrate"
version = "0.1.0"
edition = "2024"

[dependencies]
# Shared dependencies inherited from the workspace
anyhow = { workspace = true }
clap = { workspace = true }
kms-db = { workspace = true }
sqlx = { workspace = true, features = ["migrate"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Project-specific dependencies
dotenvy = { workspace = true }